spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab3
    password: lalala
    username: neonik
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  secret: 3RH7aHFDcWmpvtvAUhssAPSWheh87wWtu52HQvdlkDch7JkGrnKVsh9FJknroEC2
  exp: 10 080 # week (set in minutes)